# variables:
#   DOCKER_DRIVER: overlay2
#   DOCKER_HOST: tcp://localhost:2375

image: maven:3.5.4-jdk-8-alpine

services:
  - docker:dind

stages:
  - test

test:
  stage: test
  only:
    - master
  before_script:
    - apk add --no-cache curl jq python py-pip make
    - pip install docker-compose
  script:
    - make test
